### ISSUE TITLE
[Feature] 신고페이지

### ISSUE THREAD

**Issue by jwo1024** [PinTogether/frontend#111]
* 적용 페이지 : 신고페이지

## 내용
신고페이지 구현

## TODO
- [x] 신고페이지 css 구현
- [x] 신고페이지 api 연결
- [x] 신고 조회 페이지 css 구현
