### ISSUE TITLE
[Feature] 지도에 collection 기반 마커 띄우기

### ISSUE THREAD

**Issue by UMGGG** [PinTogether/frontend#43]
* 적용 페이지 : ex) 로그인 페이지

## 내용
지도에 collection에 있는 pin 기반 마커 띄우기

## TODO
- [x] 마커 띄우기
- [x] pin 이름 띄우기
- [x] 클릭 이벤트 추가하기
- [x] 보이는 영역의 마커만 띄우기
- [x] 지도에 collection 기반 마커 띄우기
- [x] 지도에서 사용되는 각종 기능들 깔끔하게 최적화하기
- [x] 지도를 매번 새로 만드는 방식에서 처음 만든 지도를 계속 사용하는 방식으로 새로 만들기
- [x] 클러스터링
- [x] 변경된 마커에서 가끔 이상한 모양으로 생성되는 오류 해결하기
- [x] 줌에 따라 마커의 위치가 이상해지는 문제 해결하기 (임시방편으로 크기를 늘리고 고정해서 해결했으나 클릭 영역이 겹치는 문제 발생)
- [x] 초기 접속을 컬렉션페이지에서 했을때 마커가 계속해서 남아있는 문제 해결하기
- [x] 클릭시 겹치는 마커 목록들 띄워주고 클릭해서 페이지 이동
- [x] 페이지 이동시 새로고침 문제 (<a>태그가 아닌 router 사용해야하는데 아무리 해봐도 HTML DOM에서 사용할수가 없음..)
- [x] 클러스터된 마커에 이벤트 추가하고 updateMarker 변경해주기
